-- MySQL Script generated by MySQL Workbench
-- Sun Jul  9 18:42:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fishits
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fishits
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fishits` DEFAULT CHARACTER SET utf8mb4 ;
USE `fishits` ;

-- -----------------------------------------------------
-- Table `fishits`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`fish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`fish` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`locations` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `latitude` DOUBLE(10,6) NOT NULL,
  `longitude` DOUBLE(10,6) NOT NULL,
  `s` DOUBLE(10,6) NOT NULL,
  `e` DOUBLE(10,6) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`personal_access_tokens` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC),
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`shipType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`shipType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `machine` VARCHAR(255) NULL,
  `bbm` DOUBLE(10,6) NULL,
  `speed` DOUBLE(10,6) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishits`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'user',
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `shipType_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  UNIQUE INDEX `users_username_unique` (`username` ASC),
  INDEX `fk_users_shipType1_idx` (`shipType_id` ASC),
  CONSTRAINT `fk_users_shipType1`
    FOREIGN KEY (`shipType_id`)
    REFERENCES `fishits`.`shipType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`users_has_fish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`users_has_fish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `fish_id` BIGINT(20) UNSIGNED NOT NULL,
  `berat` BIGINT NULL,
  `satuanBerat` VARCHAR(255) NULL,
  `harga` BIGINT NULL,
  `bbmTerpakai` DOUBLE(10,6) NULL,
  `jarakTempuh` DOUBLE(10,6) NULL,
  `pengeluaran` INT NULL,
  `pendapatan` INT NULL,
  `keuntungan` INT NULL,
  `tanggal` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_fish_fish1_idx` (`fish_id` ASC),
  INDEX `fk_users_has_fish_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_fish_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `fishits`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_fish_fish1`
    FOREIGN KEY (`fish_id`)
    REFERENCES `fishits`.`fish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fishits`.`regionPic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`regionPic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `month` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishits`.`pendaratans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`pendaratans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `berat` BIGINT NULL,
  `harga` BIGINT NULL,
  `nilaiProduksi` BIGINT NULL,
  `monthYear` VARCHAR(6) NULL,
  `fish_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pendaratan_fish1_idx` (`fish_id` ASC),
  CONSTRAINT `fk_pendaratan_fish1`
    FOREIGN KEY (`fish_id`)
    REFERENCES `fishits`.`fish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishits`.`bubbles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fishits`.`bubbles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` DECIMAL NULL,
  `latitude` DECIMAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
